In [2]:
import numpy as np

### Q1

In [3]:
#a Reverse the Numpy array
arr= np.array([1,2,3,6,4,5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 6 3 2 1]


In [5]:
#b Flatten the array
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
flat1 = array1.flatten()
print("original array")
print(array1)
#Method 2
flat2 = array1.ravel()
print("Flaten array :")
print("1st Method : ",flat1)
print("2st Method : ",flat2)

original array
[[1 2 3]
 [2 4 5]
 [1 2 3]]
Flaten array :
1st Method :  [1 2 3 2 4 5 1 2 3]
2st Method :  [1 2 3 2 4 5 1 2 3]


In [7]:
#c Compare two arrays
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print("Comparison between two arrays : ",np.array_equal(arr1,arr2))


Comparison between two arrays :  True


In [10]:
#d Most Frequent and indices
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])

# For x
val_x = np.bincount(x).argmax()
indices_x = np.where(x == val_x)[0]

# For y
val_y = np.bincount(y).argmax()
indices_y = np.where(y == val_y)[0]

print(f"Most Freqent value for x : {val_x}\n indices for x : {indices_x}")
print(f"Most Freqent value for y : {val_y}\n indices for y : {indices_y}")


Most Freqent value for x : 1
 indices for x : [0 5 7 8 9]
Most Freqent value for y : 1
 indices for y : [0 1 2]


In [11]:
#e Matrix sums
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

total_sum = np.sum(gfg)
row_sum = np.sum(gfg, axis=1)
col_sum = np.sum(gfg, axis=0)

print("Total sum : \n",total_sum)
print("Row sum : \n",row_sum)
print("Col sum : \n",col_sum)


Total sum : 
 45
Row sum : 
 [[14]
 [16]
 [15]]
Col sum : 
 [[20  9 16]]


In [12]:
#f matrix operations
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

# i. Sum of diagonal
diag_sum = np.trace(n_array)

# ii. Eigen values & vectors
eigen_vals, eigen_vecs = np.linalg.eig(n_array)

# iii. Inverse
inverse = np.linalg.inv(n_array)

# iv. Determinant
det = np.linalg.det(n_array)

print("Diagonal sum : \n",diag_sum)
print("Eign Values : \n",eigen_vals)
print("Eigen Vector : \n",eigen_vecs)
print("Inverse Matrix : \n",inverse)
print("Determinant : \n",det)


Diagonal sum : 
 176
Eign Values : 
 [98.16835147 28.097044   49.73460452]
Eigen Vector : 
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse Matrix : 
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant : 
 137180.0000000001


In [14]:
#(g) Matrix multiplication & covariance
# First case
p1 = np.array([[1,2],[2,3]])
q1 = np.array([[4,5],[6,7]])

mul1 = np.dot(p1,q1)

# Flatten both for covariance
cov1 = np.cov(p1.flatten(), q1.flatten())

# Second case
p2 = np.array([[1,2],[2,3],[4,5]])
q2 = np.array([[4,5,1],[6,7,2]])

mul2 = np.dot(p2,q2)

cov2 = np.cov(p2.flatten(), q2.flatten())

print("Matrix multiplication (1):\n", mul1)
print("Covariance (1):\n", cov1)

print("\nMatrix multiplication (2):\n", mul2)
print("Covariance (2):\n", cov2)



Matrix multiplication (1):
 [[16 19]
 [26 31]]
Covariance (1):
 [[0.66666667 1.        ]
 [1.         1.66666667]]

Matrix multiplication (2):
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance (2):
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [14]:
# (h) Inner, outer, cartesian product
x = np.array([[2,3,4],[3,2,9]])
y = np.array([[1,5,0],[5,10,3]])

inner = np.inner(x, y)
outer = np.outer(x, y)
cartesian = np.cross(x, y)

print("Inner Product : \n",inner)
print("outer product : \n", outer)
print("Cartestian product : \n",cartesian)


Inner Product : 
 [[17 52]
 [13 62]]
outer product : 
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartestian product : 
 [[-20   4   7]
 [-84  36  20]]


### Q2: Mathematics & Statistics

In [17]:
# (a) Array calculations
array = np.array([[1,-2,3],[-4,5,-6]])

# i. Absolute
abs_val = np.abs(array)
print("Absolute Value : \n",abs_val)
# ii. Percentiles
flat = array.flatten()
percentiles_flat = np.percentile(flat, [25,50,75])
percentiles_col = np.percentile(array, [25,50,75], axis=0)
percentiles_row = np.percentile(array, [25,50,75], axis=1)
print("percentile_flat : \n",flat)
print("percentiil_col : \n",percentiles_col)
print("percentile row : \n",percentiles_row)
# iii. Mean, Median, Std
mean_flat, median_flat, std_flat = np.mean(flat), np.median(flat), np.std(flat)
mean_col, median_col, std_col = np.mean(array,axis=0), np.median(array,axis=0), np.std(array,axis=0)
mean_row, median_row, std_row = np.mean(array,axis=1), np.median(array,axis=1), np.std(array,axis=1)
print("Mean_Flat : \n",mean_flat)
print("Median_Flat : \n",median_flat)
print("Standar_Deviation_Flat : \n",std_flat)
print("Mean_col : \n",mean_col)
print("Median_col : \n",median_col)
print("Standar_Deviation_col : \n",std_col)
print("Mean_row : \n",mean_row)
print("Median_row : \n",median_row)
print("Standar_Deviation_row : \n",std_row)


Absolute Value : 
 [[1 2 3]
 [4 5 6]]
percentile_flat : 
 [ 1 -2  3 -4  5 -6]
percentiil_col : 
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
percentile row : 
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean_Flat : 
 -0.5
Median_Flat : 
 -0.5
Standar_Deviation_Flat : 
 3.8622100754188224
Mean_col : 
 [-1.5  1.5 -1.5]
Median_col : 
 [-1.5  1.5 -1.5]
Standar_Deviation_col : 
 [2.5 3.5 4.5]
Mean_row : 
 [ 0.66666667 -1.66666667]
Median_row : 
 [ 1. -4.]
Standar_Deviation_row : 
 [2.05480467 4.78423336]


In [18]:
# (b) Floor, Ceil, Truncate, Round
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6,1.8,3.0])

floor = np.floor(a)
ceil = np.ceil(a)
trunc = np.trunc(a)
round_val = np.round(a)

print("Floor : \n",floor)
print("ceil : \n", ceil)
print("trunc : \n", trunc)
print("round : \n", round_val)


Floor : 
 [-2. -2. -1.  0.  1.  1.  3.]
ceil : 
 [-1. -1. -0.  1.  2.  2.  3.]
trunc : 
 [-1. -1. -0.  0.  1.  1.  3.]
round : 
 [-2. -2. -0.  0.  2.  2.  3.]


### Q3: Searching & Sorting

In [ ]:
# (a) Sorting
array = np.array([10,52,62,16,16,54,453])

sorted_arr = np.sort(array)
indices = np.argsort(array)
smallest4 = np.sort(array)[:4]
largest5 = np.sort(array)[-5:]

print("sorted array : \n",sorted_arr)
print("indices : \n", indices)
print("smallest4 : \n", smallest4)
print("largest 5 : \n", largest5)


sorted array : 
 [ 10  16  16  52  54  62 453]
indices : 
 [0 3 4 1 5 2 6]
smallest4 : 
 [10 16 16 52]
largest 5 : 
 [ 16  52  54  62 453]


In [21]:
# (b) Integers and float values only
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integers = array[np.floor(array) == array]
floats = array[np.floor(array) != array]

print("intgers : \n",integers)
print("float : \n", floats)


intgers : 
 [1. 2. 3. 2.]
float : 
 [1.2 2.2]


### Q4: Image Handling

In [22]:
# (a) Function to save image as array
from PIL import Image

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if len(arr.shape) == 2:  # Grayscale
        np.savetxt("image_gray.txt", arr, fmt="%d")
    else:  # RGB
        arr_reshaped = arr.reshape(-1, arr.shape[-1])
        np.savetxt("image_rgb.txt", arr_reshaped, fmt="%d")
    return "Saved Successfully"


In [24]:
# (b) Load saved file
# Example: for grayscale
loaded = np.loadtxt("D:\Courses\Machine Learning\Class Assignment\image_gray.txt")
print(loaded.shape)

# For RGB
loaded_rgb = np.loadtxt("D:\Courses\Machine Learning\Class Assignment\image_rgp.txt")
print(loaded_rgb.shape)


(0,)
(0,)


C:\Users\kansa\AppData\Local\Temp\ipykernel_16800\4259483865.py:3: UserWarning: loadtxt: input contained no data: "D:\Courses\Machine Learning\Class Assignment\image_gray.txt"
  loaded = np.loadtxt("D:\Courses\Machine Learning\Class Assignment\image_gray.txt")
C:\Users\kansa\AppData\Local\Temp\ipykernel_16800\4259483865.py:7: UserWarning: loadtxt: input contained no data: "D:\Courses\Machine Learning\Class Assignment\image_rgp.txt"
  loaded_rgb = np.loadtxt("D:\Courses\Machine Learning\Class Assignment\image_rgp.txt")
